config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :faqs
  resources :withdraws
  resources :trades
  resources :deposits
  resources :accounts
  resources :pages, only: [:show]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :home, only: [:new, :create]

  ActiveAdmin.routes(self)

  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
root 'home#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  extend FriendlyId
  friendly_id :address, use: :slugged

  belongs_to :user
  has_many :trades
  validates :user, presence: true
  validates :balance, presence: true
  validates :understood, presence: true
  validates :guranted, presence: true

  validates :address, presence: true, uniqueness: true
  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.balance = 0.00
      self.ctp = 0.00
      self.capital = 0.00
      self.roi = 0.00

      self.closing_b = 0.00
      self.opening_b = 0.00
      self.profit_bf = 0.00
      self.gross_pl = 0.00
      self.net_pl = 0.00
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user

end

app/models/faq.rb
class Faq < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/home.rb
class Home < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@xpressbittrade.com",
        :from => %("#{name}", "#{email}")
      }
    end
end

app/models/pool.rb
class Pool < ApplicationRecord
  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.pool_ob == 0
      self.pool_cl == 0
      self.pool_pl == 0
      self.tob == 0
    end
  end
end

app/models/trade.rb
class Trade < ApplicationRecord

  belongs_to :account

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
has_many :accounts, dependent: :destroy
has_many :deposits, dependent: :destroy
has_many :withdraws, dependent: :destroy
end

app/models/welcome.rb
class Welcome < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@nunuexchange.com",
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :user
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/layouts/accounts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptontrade  || Online  Account </title>
    <%= csrf_meta_tags %>
    <meta name="description" content="Invest and reap rewards from  our investment mechanism created by the best proffessionals in the field"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'accounts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'accounts', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
  <%= render "shared/sidebar" %>
      <%= render "shared/headermenu" %>

      <% if notice %>
      <div class="col-md-8 col-md-offset-2">


      <div class="alert alert-info alert-with-icon" data-notify="container">
                                    <button type="button" aria-hidden="true" class="close">×</button>
                                    <span data-notify="icon" class="ti-bell"></span>
                                    <span data-notify="message"><%= notice %>.</span>
                                </div>
                              </div>
                                <% end %>

    <%= yield %>

      </div>
    </div>
    <script>
  (function(b,i,t,C,O,I,N) {
    window.addEventListener('load',function() {
      if(b.getElementById(C))return;
      I=b.createElement(i),N=b.getElementsByTagName(i)[0];
      I.src=t;I.id=C;N.parentNode.insertBefore(I, N);
    },false)
  })(document,'script','https://widgets.bitcoin.com/widget.js','btcwdgt');
</script>
  </body>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptontrades || Start Trading with
      cryptocurrencies without
       risk on the best crypto-trading platform </title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description"  content="you dont need to know everything about the block chain before investing into it. start trading today at best rates ever"/>
    <meta name="keywords" content="Binary Options,Investment , learn, Bitcoin trade, Best Cashback Investment Program">
    <meta name="MobileOptimized" content="320">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  <body class="trd-home-template trd-homepage-six">
    <%= render "shared/header" %>
    <% if notice %>
    <div class="container" style="position:absolute; top:100px; left:210px; z-index:999;">
      <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-success fade in">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <p><%= notice %> </p>
        </div>
      </div>
    </div>
    <% elsif alert %>
    <div class="container" style="position:absolute; top:100px; left:210px; z-index:999;">
      <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-danger fade in">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <p><%= alert %></p>
        </div>
      </div>
    </div>
    <% end %>


    <%= yield %>
    <%= render "shared/footer" %>
    <script>
  (function(b,i,t,C,O,I,N) {
    window.addEventListener('load',function() {
      if(b.getElementById(C))return;
      I=b.createElement(i),N=b.getElementsByTagName(i)[0];
      I.src=t;I.id=C;N.parentNode.insertBefore(I, N);
    },false)
  })(document,'script','https://widgets.bitcoin.com/widget.js','btcwdgt');
</script>
  </body>
</html>

app/views/shared/_banner.html.erb
<!-- HERO SLIDER SECTION -->
<section class="trd-hero-slider-section">
    <div class="slider-pro trd-hero-slider" id="trd-fullscreen-slider">
        <div class="sp-slides">

            <!-- Slides -->
            <div class="sp-slide trd-main-slides">
              <div class="trd-dark-color-overlay"></div>

                <!-- <div class="az-dark-color-overlay"></div> -->
                <%= image_tag "1.jpg", class: "sp-image" %>

                <h1 class="sp-layer trd-slider-text-big"
                 data-position="centerLeft" data-vertical="-230"  data-horizontal="100"  data-show-transition="left" data-hide-transition="up" data-show-delay="1000" data-hide-delay="200">
                Proper<span class="trd-highlight-text"> Trades Executed To Convey Best</span><br> Returns With Up to 100% GUARANTEE on capital


                 </h1>


                 <div class="sp-layer trd-hero-header-btns" data-position="centerLeft" data-vertical="200" data-horizontal="100" data-show-delay="2000" data-hide-delay="200" data-show-transition="down" data-hide-transition="up">
                     <a href="#how" class="trd-btn">Details</a>
                     <%= link_to new_user_registration_path, class: " trd-btn trd-btn-purple " do %>
                     Sign Up
                     <% end %>
                 </div>
            </div>
            <!-- Slides End -->


            <!-- Slides -->
            <div class="sp-slide trd-main-slides">
              <div class="trd-dark-color-overlay"></div>

                <!-- <div class="az-dark-color-overlay"></div> -->
                <%= image_tag "btc.jpg", class: "sp-image" %>


                                <h1 class="sp-layer trd-slider-text-big"
                                 data-position="centerLeft" data-vertical="-230"  data-horizontal="100"  data-show-transition="left" data-hide-transition="up" data-show-delay="1000" data-hide-delay="200">
                                Proven And Reliable Algorithms <span class="trd-highlight-text"style="color:#fff;"> Executing Trades</span>
                 </h1>



                 <div class="sp-layer trd-hero-header-btns" data-position="centerLeft" data-vertical="200" data-horizontal="100" data-show-delay="2000" data-hide-delay="200" data-show-transition="down" data-hide-transition="up">
                     <a href="#how" class="trd-btn">Details</a>
                     <%= link_to new_user_registration_path, class: " trd-btn trd-btn-purple " do %>
                     Sign Up
                     <% end %>
                 </div>
            </div>
            <!-- Slides End -->

        </div>
    </div>
</section>
<!-- HERO SLIDER SECTION END -->



<!-- HERO SLIDER SECTION END -->



<!-- SERVICE SECTION -->
<section class="trd-service-section trd-section">
    <div class="container">
        <div class="row">
            <!-- Icon with text -->
            <div class="col-md-4 col-sm-4 col-xs-12 trd-icon-top-with-text">
                <div class="trd-icon-wrapper">
                    <i class="tradeicon-trd-coffee-mug"></i>
                </div>

                <div class="trd-details">
                    <h3>
                        <a href="#">Simple exchange platform</a>
                    </h3>

                    <p>Enjoy comprehensive yet simplistic means of executing trades on our platform with dedicated tools for transparent analysis.</p>
                </div>
            </div>
            <!-- End -->

            <!-- Icon with text -->
            <div class="col-md-4 col-sm-4 col-xs-12 trd-icon-top-with-text">
                <div class="trd-icon-wrapper">
                    <i class="tradeicon-trd-trophy"></i>
                </div>

                <div class="trd-details">
                    <h3>
                        <a href="#">Best Consultancy</a>
                    </h3>

                    <p>Our best traders are available for
interaction on cryptocurrency pairs
everyday of the week.</p>
                </div>
            </div>
            <!-- End -->

            <!-- Icon with text -->
            <div class="col-md-4 col-sm-4 col-xs-12 trd-icon-top-with-text">
                <div class="trd-icon-wrapper">
                    <i class="tradeicon-trd-chart-board"></i>
                </div>

                <div class="trd-details">
                    <h3>
                        <a href="#">Open Market Trade</a>
                    </h3>

                    <p>We place trades on all
cryptocurrency pairs that have been
listed on exchanges.</p>
                </div>
            </div>
            <!-- End -->
        </div>
    </div>
</section>
<section class="trd-custom-section trd-gray-section">
    <div class="container">
        <div class="row">

            <div class="trd-process-step-wrapper">
                <div class="trd-process-step-wrapper col-md-4 col-sm-4 col-xs-12">
                    <div class="trd-process-step">
                        <div class="trd-step-img-wrapper">
                            <%= image_tag "step-1.jpg" %>
                        </div>

                        <div class="trd-step-details-wrapper">
                            <%= link_to new_user_session_path do %><span>01</span> Market Analysis<%end%>                          </div>
                    </div>
                </div>

                <div class="trd-process-step-wrapper col-md-4 col-sm-4 col-xs-12">
                    <div class="trd-process-step">
                        <div class="trd-step-img-wrapper">
                          <%= image_tag "step-2.jpg" %>
                        </div>

                        <div class="trd-step-details-wrapper">
                            <%= link_to new_user_session_path do %><span>02</span> Start Trade <%end%>
                        </div>
                    </div>
                </div>

                <div class="trd-process-step-wrapper col-md-4 col-sm-4 col-xs-12">
                    <div class="trd-process-step">
                        <div class="trd-step-img-wrapper">
                            <%= image_tag "step-3.jpg" %>

                        </div>

                        <div class="trd-step-details-wrapper">
                            <%= link_to new_user_session_path do %><span>03</span> Increase Profits<%end%>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- KEY TO SUCCESS SECTION -->
<section class="trd-we-are-section trd-section">
  <div class="container">
    <div class="row">
      <div class="trd-section-title-wrapper col-md-12 col-sm-12 col-xs-12">
        <h1 class="trd-section-tittle">We Make  <span class="trd-highlight-text">Crypto Trading Simple, Profitable and Accessible to all </span></h1>
      </div>


      <div class="trd-we-are-trade">

        <!-- Imagebox with Text -->
        <div class="col-md-3 col-sm-6 col-xs-12 trd-imagebox-with-text-wrapper trd-fade-imgbox-text">
          <div class="trd-imagebox-with-text">
            <div class="trd-image-wrapper">
              <%= image_tag "imgbox-img-7.jpg" %>
            </div>

            <div class="trd-imagebox-details">
              <h3>
                <a href="#">Proper Planing</a>
              </h3>
              <p>
With years of
experience trading
cryptocurrency we
execute properly
planned market
entry/exit strategies</p>
              </div>
            </div>
          </div>
          <!-- End -->

          <!-- Imagebox with details -->
          <div class="col-md-3 col-sm-6 col-xs-12 trd-imagebox-with-text-wrapper trd-fade-imgbox-text">
            <div class="trd-imagebox-with-text ">
              <div class="trd-image-wrapper">
                <%= image_tag "imgbox-img-6.jpg" %>
              </div>

              <div class="trd-imagebox-details">
                <h3>
                  <a href="#">Easy Exchange Platform </a>
                </h3>
                <p>
Crypto options have several
advantages one of which
includes maintaining high
liquidity do you know you can
exchange your cash for
cryptocurrency and vice versa
easily.  </p>
              </div>
            </div>
          </div>
          <!-- End -->

          <!-- Imagebox with details -->
          <div class="col-md-3 col-sm-6 col-xs-12 trd-imagebox-with-text-wrapper trd-fade-imgbox-text">
            <div class="trd-imagebox-with-text">
              <div class="trd-image-wrapper">
                <%= image_tag "imgbox-img-5.jpg" %>
              </div>

              <div class="trd-imagebox-details">
                <h3>
                  <a href="#">Consulting</a>
                </h3>
                <p>Consult Our Experts
On the best way to
manage your crypto
assets.</p>
              </div>
            </div>
          </div>
          <!-- End -->

          <!-- Text with link -->
          <div class="col-md-3 col-sm-6 col-xs-12 trd-text-link-section">
            <div class="trd-text-link-wrapper trd-gray-section">
              <h1 class="trd-section-tittle">Let’s make <br> <span class="trd-highlight-text"> Business</span>better</h1>
              <p>
Buisness And
Money Should Be
Working For You.
Lets Make That
Happen </p>

            </div>
          </div>
          <!-- End -->

        </div>
      </div>
    </div>
  </section>
  <!-- KEY TO SUCCESS SECTION END -->
<!-- SERVICE SECTION END -->
<%= render "shared/btc" %>
<br />

<!-- CLIENT LOGO CAROUSAL END -->
<%= render "shared/success" %>

        <!-- COUNTER SECTION END -->
        <%= render "shared/pricing" %>
        <!-- CUSTOM SECTION -->

        <!-- CUSTOM SECTION END -->

        <br />

        <%= render "shared/cta"%>

app/views/shared/_btc.html.erb
<section class="trd-about-business-section trd-section">
    <div class="container">
        <div class="row">
            <!-- About Business -->

            <div class="col-md-6  ">
                <div style="width:100%; max-width:100% !important;" class="btcwdgt-chart"></div>
            </div>

            <div class="col-md-6">

                     <h3>What's Best Is... </h3>
                   <p> Join Our 100% auto trading platform for  Crypto Options which generates trading
                    signals and automatically executes trades directly to a user’s linked broker account. Offering traders a
                    professional signals service which looks set to surpass its competitors,
                     is fast gaining popularity within the trading community.

                          <strong>  An attractive aspect of this software is that no previous  Crypto Options trading knowledge is required to use the service.
                             It’s just a case of signing up with  and opening an account.</p>

                             <br/>
                    <h3>We ensure the highest level of security for all our investors </h3>
                    <strong>cryptontrade is dedicated to your security and uses the best encryption software possible for all personal and financial information, including SSL encryption through HTTPS secure web protocols. Furthermore, all trader funds are kept in segregated accounts and cannot be touched by brokers for anything other than trading purposes.</strong>
            </div>
            <!-- End -->


        </div>
    </div>

</section>

app/views/shared/_cta.html.erb
<!-- CTA SECTION -->
<section class="trd-cta-section">
   <div class="container">
       <div class="row">
           <div class="trd-cta-wrapper">
               <h3>Get in touch with us for   <span class="trd-highlight-text">the best results on your investments</span> and how to make our
platform work for you.</h3>
               <%= link_to "Get Started", new_user_registration_path, class: "trd-btn trd-btn-alt" %>
           </div>
       </div>
   </div>
</section>
<!-- CTA SECTION END -->

app/views/shared/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <!-- Footer Top -->
            <div class="trd-footer-top">
                <!-- About Widget -->
                <div class="col-md-3 col-sm-6 col-xs-12 trd-footer-widget trd-about-widget">

                  <div class="trd-logo-wrapper">
                      <%= image_tag "footer.png"  %>
                  </div>
                    <p>Lets Make Money For You</p>
                </div>
                <!-- End -->

                <!-- Useful Link Widget -->
                <div class="col-md-3 col-sm-6 col-xs-12 trd-footer-widget trd-useful-link-widget">
                    <h3 class="trd-footer-widget-title">Useful Link</h3>

                    <div class="trd-footer-widget-content">
                        <ul>
                          <li c>
                            <%= link_to "Home", root_path %>
                          </li>
                          <li>
                            <%= link_to "About Us", page_path('about') %>
                          </li>

                          <li>
                              <%= link_to "FAQ's", faqs_path  %>

                          </li>

                          <li><%= link_to new_user_registration_path do %>
                              <i class="fa fa-user"> Login/SignUp</i>
                          <%end%> </li>
                    </div>
                </div>
                <!-- End -->


                <!-- Subscribe For Widget -->
                <div class="col-md-3 col-sm-6 col-xs-12 trd-footer-widget trd-subscribe-widget">
                    <h3 class="trd-footer-widget-title">Subscribe</h3>

                    <div class="trd-footer-widget-content">
                        <p>We Dont Disturb Much</p>

                        <form action="#">
                            <input type="email" name="trd-subscription" id="trd-subscription" placeholder="Your email">
                            <button type="submit" class="trd-btn">Submit</button>
                        </form>
                    </div>
                </div>
                <!-- End -->
            </div>
            <!-- End -->

            <!-- Footer Bottom -->
            <div class="trd-footer-bottom">
                <div class="trd-footer-menu">
                    <ul>
                      <li class="active">
                        <%= link_to "Home", root_path %>
                      </li>
                      <li>
                        <%= link_to "About Us", page_path('about') %>
                      </li>

                      <li>
                          <%= link_to "FAQ's", faqs_path  %>

                      </li>

                      <li><%= link_to new_user_registration_path do %>
                          <i class="fa fa-user"> Login/SignUp</i>
                      <%end%> </li>
                    </ul>
                </div>

                <div class="trd-copyright-info">
                    <a href="www.zonia.co">Developed By Kizonia Solutions</a>
                </div>
            </div>
            <!-- End -->
        </div>
    </div>
    <!-- End -->
</footer>
<!-- FOOTER END -->

app/views/shared/_header.html.erb
<header class="trd-header trd-transparent-header trd-fixed-header">

    <!-- Bottombar -->
    <div class="trd-header-bottombar">
        <!-- Navigation Menu start-->
        <nav class="navbar trd-main-menu" role="navigation">
          <div class="container">
            <div class="row">
              <!-- Navbar Toggle -->
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>

                  <!-- Logo -->
                  <%= link_to root_path, class: "navbar-brand" do %><%= image_tag "logo.png" %> <%end%>
              </div>
              <!-- Navbar Toggle End -->

                <!-- navbar-collapse start-->
                <div id="nav-menu" class="navbar-collapse trd-menu-wrapper collapse" role="navigation">
                    <!-- Menu -->
                    <ul class="nav navbar-nav trd-menus">
                        <li class="active">
                          <%= link_to "Home", root_path %>
                        </li>
                        <li>
                          <%= link_to "About Us", page_path('about') %>
                        </li>
                        <li>
                          <a href="#">Knowledge Base</a>
                          <ul class="trd-dropdown-menu">
                            <li>
                              <%= link_to "How It Works", page_path("How-it-works") %>
                            </li>
                            <li>
                                <%= link_to "Our Whitepaper", "https://docs.google.com/document/d/16xGHvKiwbcao2Yg4DivFm_CUeD_sOzIqhkreORVHYDo/edit?usp=sharing"  %>

                            </li>
                            <li>
                              <%= link_to "Open A Bitcoin Wallet", page_path("bitcoin") %>
                            </li>
                            <li>
                                <%= link_to "FAQ's", faqs_path  %>

                            </li>
                          </ul>
                        </li>

                        <li><%= link_to new_user_session_path do %>
                            <i class="fa fa-user"> Login</i>
                        <%end%> </li>
                        <li><%= link_to new_user_registration_path do %>
                            <i class="fa fa-user"> SignUp</i>
                        <%end%> </li>
                    </ul>
                    <!-- End -->
                </div>
                <!-- navbar-collapse end-->


            </div>
          </div>
        </nav>
        <!-- Navigation Menu end-->
    </div>
    <!-- End -->
</header>
<!-- HEADER END -->

app/views/shared/_headermenu.html.erb
<div class="main-panel">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar bar1"></span>
          <span class="icon-bar bar2"></span>
          <span class="icon-bar bar3"></span>
        </button>
        <a class="navbar-brand" href="#">Dashboard</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="ti-panel"></i>
              <p><%= current_user.email %></p>
            </a>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>

              <i class="ti-arrow-left"></i>
              <p>log out</p>
            <% end %>
          </li>
        </ul>

      </div>
    </div>
  </nav>

app/views/shared/_sidebar.html.erb
<div class="sidebar" >

<!--
Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

  <div class="sidebar-wrapper">
        <div class="logo">
            <%= current_user.email %>
        </div>

        <ul class="nav">
            <li class="active">
                <%= link_to accounts_path do %>
                    <i class="ti-panel"></i>
                    <p>Account</p>
                <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                    <i class="ti-user"></i>
                    <p>Account Profile</p>
                <% end %>
            </li>
          
            <li>
                <%= link_to deposits_path do %>
                    <i class="ti-credit-card"></i>
                    <p>Deposits</p>
                <% end %>
            </li>
            <li>
              <%= link_to withdraws_path do %>
                    <i class="ti-money"></i>
                    <p>Withdrawal</p>
                <% end %>
            </li>


            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>

                    <i class="ti-arrow-left"></i>
                    <p>Sign-out</p>
                </a>
            <% end %>

        </ul>
  </div>
</div>