config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :faqs
  resources :withdraws
  resources :trades
  resources :deposits
  resources :accounts
  resources :pages, only: [:show]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :home, only: [:new, :create]

  ActiveAdmin.routes(self)

  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
root 'home#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  extend FriendlyId
  friendly_id :address, use: :slugged

  belongs_to :user
  has_many :trades
  validates :user, presence: true
  validates :balance, presence: true
  validates :understood, presence: true
  validates :guranted, presence: true

  validates :address, presence: true, uniqueness: true
  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.balance = 0.00
      self.ctp = 0.00
      self.capital = 0.00
      self.roi = 0.00

      self.closing_b = 0.00
      self.opening_b = 0.00
      self.profit_bf = 0.00
      self.gross_pl = 0.00
      self.net_pl = 0.00
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user

end

app/models/faq.rb
class Faq < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/home.rb
class Home < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@xpressbittrade.com",
        :from => %("#{name}", "#{email}")
      }
    end
end

app/models/pool.rb
class Pool < ApplicationRecord
  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.pool_ob == 0
      self.pool_cl == 0
      self.pool_pl == 0
      self.tob == 0
    end
  end
end

app/models/trade.rb
class Trade < ApplicationRecord

  belongs_to :account

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
has_many :accounts, dependent: :destroy
has_many :deposits, dependent: :destroy
has_many :withdraws, dependent: :destroy
end

app/models/welcome.rb
class Welcome < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@nunuexchange.com",
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :user
end

app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base

  before_action :find_faqs, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_adminuser!, except: [:index, :show]
  def index
    @faqs = Faq.all.order('created_at DESC')
  end

  def show
  end

  private
  def find_faqs
    @faq = Faq.friendly.find(params[:id])
  end
  def faqs_param
      params.require(:faq).permit(:title, :body, :slug)
    end
end

app/controllers/withdraws_controller.rb
class WithdrawsController < InheritedResources::Base
  layout "accounts"
  before_action :authenticate_user!
  before_action :set_withdraw, only: [:show, :edit, :update, :destroy]

  def index
    @withdraws = Withdraw.where(user_id: current_user).order('created_at DESC')
  end

  def show
  end

  def new
    @withdraw = current_user.withdraws.build
  end

  def create
    @withdraw = current_user.withdraws.build(withdraw_params)
    @withdraw.user_id = current_user.id
    respond_to do |format|
     if @withdraw.save
        user = User.find_by_id(@withdraw.user_id)
        withdraw = @withdraw
        WithdrawMailer.withdraw_email(user, withdraw).deliver
        format.html { redirect_to root_path, notice: 'We have received your withdrawal  request we will contact you soon.' }
        format.json { render :show, status: :created, location: @withdraw }
      else
        format.html { render :new }
        format.json { render json: @withdraw.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  def set_withdraws
    @withdraw = Withdraw.find(params[:id])
  end


    def withdraw_params
      params.require(:withdraw).permit(:amount, :payment_method, :email, :user_id, :bankName, :accountNumber, :status, :acctName, :bitcoin)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/withdraws/_form.html.erb
<%= simple_form_for(@withdraw) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :amount, placeholder: "$5000", class: "form-control border-input" %>
    <%= f.input :payment_method, as: :select, :collection => [ "Bank Transfer"], class: "form-control border-input "  %>
    <%= f.input :email, class: "form-control border-input" %>
    <%= f.input :bankName, label: "Bank Name", class: "form-control border-input" %>
    <%= f.input :acctName, label: "Account Name", class: "form-control border-input" %>

    <%= f.input :accountNumber, label: "Account Number", class: "form-control border-input" %>
<p> For Bitcoin </p>
    <%= f.input :bitcoin, label: "Input Bitcoin Wallet Address", class: "form-control border-input" %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/withdraws/edit.html.erb
<h1>Editing Withdraw</h1>

<%= render 'form', withdraw: @withdraw %>

<%= link_to 'Show', @withdraw %> |
<%= link_to 'Back', withdraws_path %>

app/views/withdraws/index.html.erb
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-success text-center">
                                <i class="ti-wallet"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Withdrawal History</p>
                                <%= Withdraw.where(user_id: current_user.id).count %>


                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="ti-reload"></i> Updated now
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-success text-center">
                              <i class="ti-credit-card"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Request Funds</p>
                                <%= link_to new_withdraw_path, class: "btn btn-primary" do %>
                                   Make a withdraw
                                   <%end%>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="ti-pulse"></i> Start Trade Now
                        </div>
                    </div>
                </div>
            </div>
        </div>

      </div>

      <div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="header">
                      <h4 class="title">withdraw History</h4>
                      <p class="category">Your previous withdraws  in the last 24hrs are as follows</p>
                  </div>
                  <div class="content table-responsive table-full-width">

      <table class="table table-striped">
      <thead>
      <tr>
      <th>Amount</th>
      <th>Payment Method</th>
      <th>Email</th>
      <th>Bank Name </th>
      <th>Account Number</th>
      <th>Status</th>
      </tr>
      </thead>

      <tbody>
      <% @withdraws.each do |d| %>
      <tr>
      <td>$<%= d.amount %></td>
      <td><%= d.payment_method %></td>
      <td><%= d.email %></td>
      <td><%= d.bankName %></td>
      <td><%= d.accountNumber %></td>
      <td><% if d.status? %><a href="#" class="btn btn-success"> Paid</a> <%else %><a href="#" class="btn btn-danger">Not Confirmed</a> <% end %></td>

      </tr>
      <% end %>
      </tbody>
      </table>

                      </div>
                  </div>
              </div>


      <br>

      <%= link_to 'New withdraw', new_withdraw_path, class: "btn btn-success" %>

app/views/withdraws/new.html.erb
<div class="content">
    <div class="container-fluid">
<div class="col-md-8 col-md-offset-2">
    <div class="card">
        <div class="header">
            <h4 class="title">Make a Withdraw</h4>
        </div>
        <div class="content">
<%= render 'form', withdraw: @withdraw %>

</div>
</div>
</div>
</div>
</div>

app/views/withdraws/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @withdraw.amount %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @withdraw.payment_type %>
</p>

<p>
  <strong>Email:</strong>
  <%= @withdraw.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @withdraw.user %>
</p>

<%= link_to 'Edit', edit_withdraw_path(@withdraw) %> |
<%= link_to 'Back', withdraws_path %>