config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :faqs
  resources :withdraws
  resources :trades
  resources :deposits
  resources :accounts
  resources :pages, only: [:show]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :home, only: [:new, :create]

  ActiveAdmin.routes(self)

  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
root 'home#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  extend FriendlyId
  friendly_id :address, use: :slugged

  belongs_to :user
  has_many :trades
  validates :user, presence: true
  validates :balance, presence: true
  validates :understood, presence: true
  validates :guranted, presence: true

  validates :address, presence: true, uniqueness: true
  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.balance = 0.00
      self.ctp = 0.00
      self.capital = 0.00
      self.roi = 0.00

      self.closing_b = 0.00
      self.opening_b = 0.00
      self.profit_bf = 0.00
      self.gross_pl = 0.00
      self.net_pl = 0.00
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user

end

app/models/faq.rb
class Faq < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/home.rb
class Home < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@xpressbittrade.com",
        :from => %("#{name}", "#{email}")
      }
    end
end

app/models/pool.rb
class Pool < ApplicationRecord
  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.pool_ob == 0
      self.pool_cl == 0
      self.pool_pl == 0
      self.tob == 0
    end
  end
end

app/models/trade.rb
class Trade < ApplicationRecord

  belongs_to :account

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
has_many :accounts, dependent: :destroy
has_many :deposits, dependent: :destroy
has_many :withdraws, dependent: :destroy
end

app/models/welcome.rb
class Welcome < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@nunuexchange.com",
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :user
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  layout "accounts"
  before_action :find_account, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :find_users, only: [:index, ]
  def index
    @users = User.where(user_id: current_user)
    @accounts = Account.where(user_id: current_user).order('created_at DESC')
    @deposits = Deposit.where(user_id: current_user).order('created_at DESC')
    @trades = Trade.where(user_id: current_user).order('created_at DESC')
    @withdraws = Withdraw.where(user_id: current_user).order('created_at DESC')
  end
  def show
  end
  def new
    @account = current_user.accounts.build
  end
  def create
    @account = current_user.accounts.build(account_params)
    @account.user_id = current_user.id
    if @account.save
      user = User.find_by_id(@account.user_id)
      account = @account
      AccountMailer.account_email(user, account).deliver
      redirect_to root_path, notice: "Welcome To Your Trading Account Please Start Auto-Trade By Making A Deposit Now"
    else
      render 'new', notice: "Please Try Again"
    end
  end

  def edit

  end

  def update
    if @account.update(account_params)
      redirect_to @account
    else
      render 'edit'
    end
  end

  private
  def find_account
    @account = Account.friendly.find(params[:id])
  end

  def find_users
    if params[:id].nil?
      @user = current_user
    end
  end
    def account_params
      params.require(:account).permit(:balance, :address,  :user_id, :capital, :guranted, :gross_pl, :roi, :net_pl, :ctp, :closing_b, :opening_b, :profit_bf, :status, :understood )
    end
end

app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base

  before_action :find_faqs, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_adminuser!, except: [:index, :show]
  def index
    @faqs = Faq.all.order('created_at DESC')
  end

  def show
  end

  private
  def find_faqs
    @faq = Faq.friendly.find(params[:id])
  end
  def faqs_param
      params.require(:faq).permit(:title, :body, :slug)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :address, placeholder: "Your Bitcoin Address or Account No " %>
    <%= f.input :guranted, label: "Percentage of Capital Guaranteed", placeholder: "please note that the %Guarantee affects your commision ", as: :select, :collection => [ "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "100"] %>

  </div>


     <div class="form-actions">
       <%= f.input :understood, as: :boolean, label: "I agree to the terms and conditons provided" %>

    <%= f.button :submit %>
  </div>

<% end %>
<br>
  <div class="texr-center">
    <div class="small">
      <a href="https://docs.google.com/document/d/16xGHvKiwbcao2Yg4DivFm_CUeD_sOzIqhkreORVHYDo/edit?usp=sharing">Terms And Conditions Apply*</a>
    </div>
  </div>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="content">
    <div class="container-fluid">
      <% if Account.where(user_id: current_user.id).exists?%>
        <div class="row">
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-success text-center">
                                  <i class="ti-wallet"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Account Balance</p>
                                <% @accounts.take(1).each do |a| %>

                                  $<%= a.balance %>

                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-danger text-center">
                                  <i class="ti-bar-chart"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Capital</p>
                                  $<%= a.capital %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                            <%= link_to a, class: "btn btn-warning" do %>
                               View Trade History
                               <%end%>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                            <% if a.status? %>
                              <div class="icon-big icon-danger text-center">
                                  <i class="ti-shortcode"></i>
                              </div>
                               <%else %>
                               <div class="icon-big icon-danger text-center">
                                   <i class="ti-money"></i>
                               </div>
                               <%end%>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Capital Guranted</p>
                                  <%= a.guranted %>%
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-danger text-center">
                                  <i class="ti-pulse"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Gross profit/loss</p>
                                $  <%= a.gross_pl %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-danger text-center">
                                  <i class="ti-stats-down"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Net profit/loss</p>
                                $<%= a.net_pl %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-danger text-center">
                                  <i class="ti-pulse"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>ROI</p>
                                  <%= a.roi %>%
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <%end%>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-success text-center">
                                  <i class="ti-credit-card"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Deposits</p>
                                  <%= Deposit.where(user_id: current_user.id).count %>

                              </div>
                          </div>

                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                             <%= link_to new_deposit_path, class: "btn btn-primary" do %>
                                Make a Deposit
                                <%end%>
                          </div>
                      </div>

                  </div>
              </div>
          </div>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-danger text-center">
                                  <i class="ti-money"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Withdrawals</p>
                                  <%= Withdraw.where(user_id: current_user.id).count %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                            <%= link_to new_withdraw_path, class: "btn btn-primary" do %>
                               Withdraw Funds
                               <%end%>
                          </div>
                      </div>

                  </div>
              </div>
          </div>
      </div>
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="row">
                <div class="col-md-12 embed-responsive embed-responsive-16by9">

                  <div style="width:100%; max-width:100% !important;" class="btcwdgt-chart"></div>


          </div>
              </div>

            </div>
          </div>
      </div>
     <% else %>
     <div class="row" style="margin-top:50px;">
       <div class="col-md-8 col-md-offset-2">


       <div class="card">
         <div class="image">
           <%= image_tag "home7-slider-img-1.jpg", class: "img-fluid" %>
         </div>
         <div class="content">
           <div class="header text-center">
               <h4 class="title">Start making your life easier</h4>
               <br />
             <%= link_to "Create Your Trading Account", new_account_path, class: "btn btn-primary text-center"%>
</div>
         </div>

       </div>
     </div>
      </div>
<% end %>

    </div>
</div>

app/views/accounts/new.html.erb
<div class="content">
    <div class="container-fluid">
<div class="col-md-8 col-md-offset-2">
    <div class="card">
        <div class="header">
            <h4 class="title">New Account</h4>
        </div>
        <div class="content">
<%= render 'form', account: @account %>

</div>
</div>
</div>
</div>
</div>

app/views/accounts/show.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header">
            <h4 class="title">Trade History</h4>
            <p class="category">Here are trade result in the last 24hrs</p>
          </div>
          <div class="content table-responsive table-full-width">
            <table class="table table-striped">

              <thead>
                <tr>
                  <th>Date</th>
                  <th>Opening Balance</th>
                  <th>Commission Rate</th>
                  <th>Gross profit/loss</th>
                  <th>Net profit/loss </th>
                  <th>Closing Balance</th>
                  <th>Returns On Investment</th>

                  <th>Capital</th>
                  <th>Gurantee</th>
                




                </tr>
              </thead>
              <tbody>

                <%= render @account.trades.reverse %>

              </tbody>
            </table>

          </div>
        </div>
      </div>